name = "sms-otp-worker"
main = "cloudflare-worker.js"
compatibility_date = "2024-09-23"

[vars]
# Add environment variables here if needed

[[durable_objects.bindings]]
name = "OTP"
class_name = "OtpStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OtpStore"]
